services:
  humanitz:
    build:
      context: ./humanitz
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    stop_grace_period: 2m
    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
